framework: ~
services:
  _defaults:
    autoconfigure: true
    autowire: true
  League\CommonMark\Environment\Environment:
    calls:
      - addExtension: ['@League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension']
  League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension: ~
  League\CommonMark\MarkdownConverter:
    arguments: ['@League\CommonMark\Environment\Environment']
  logger:
    alias: Psr\Log\NullLogger
  Psr\Log\NullLogger: ~
  TJM\Wiki\Wiki:
    arguments: ['%kernel.project_dir%/wiki']
  TJM\WikiWeb\FormatConverter\MarkdownConverter:
    arguments: ['@League\CommonMark\MarkdownConverter']
  TJM\WikiWeb\WikiWeb:
    arguments:
      $opts:
        converters:
          - '@TJM\WikiWeb\FormatConverter\MarkdownConverter'
    tags:
      - 'controller.service_arguments'
      -
        event: 'kernel.exception'
        method: 'handleException'
        name: 'kernel.event_listener'
